//------------------------------------------------------------------------------
//     AUTHORING
//------------------------------------------------------------------------------
/**
 * @file physics.hpp
 * @author Rayan MALEK
 * @date 2026-02-19
 * @brief Definition of the Physics class for managing molecular Hamiltonian
 * data.
 */

#pragma once

//------------------------------------------------------------------------------
//     INCLUDES
//------------------------------------------------------------------------------

#include <algorithm>
#include <complex>
#include <fstream>
#include <iostream>
#include <nlohmann/json.hpp>
#include <quest.h>
#include <spdlog/spdlog.h>
#include <string>
#include <vector>

//------------------------------------------------------------------------------
//     CLASS DECLARATION
//------------------------------------------------------------------------------

/**
 * @class Physics
 * @brief Handles the loading and representation of the molecular Hamiltonian.
 *
 * Reads Hamiltonian data from a JSON file (generated by python scripts),
 * converts it into QuEST compatible structures (PauliStrSum), and provides
 * accessors for simulation properties like electron count and Pauli strings.
 */
class Physics {
public:
        //----------------------------------------------------------------------------
        //     CONSTRUCTOR / DESTRUCTOR
        //----------------------------------------------------------------------------

        /**
         * @brief Constructs a new Physics object.
         *
         * Automatically loads the Hamiltonian from the specified file upon
         * construction.
         *
         * @param filename Path to the JSON file containing Hamiltonian data.
         */
        Physics(const std::string &filename);

        /**
         * @brief Destructor.
         */
        ~Physics() = default;

        //----------------------------------------------------------------------------
        //     GETTERS
        //----------------------------------------------------------------------------

        /**
         * @brief Gets the number of qubits in the system.
         * @return int Number of qubits.
         */
        int get_num_qubits() const;

        /**
         * @brief Gets the number of Pauli terms in the Hamiltonian.
         * @return int Number of terms.
         */
        int get_num_terms() const;

        /**
         * @brief Gets the QuEST representation of the Hamiltonian.
         * @return PauliStrSum The Hamiltonian sum.
         */
        PauliStrSum get_quest_hamiltonian() const;

        /**
         * @brief Gets the list of Pauli strings strings (e.g., "X0 Y1").
         * @return const std::vector<std::string>& Vector of strings.
         */
        const std::vector<std::string> &get_pauli_strings() const;

        /**
         * @brief Gets the coefficients associated with the Pauli strings.
         * @return const std::vector<qcomp>& Vector of coefficients.
         */
        const std::vector<qcomp> &get_coefficients() const;

        //----------------------------------------------------------------------------
        //     METADATA
        //----------------------------------------------------------------------------

        /**
         * @brief Gets the number of orbitals.
         * @return int Number of orbitals.
         */
        int get_n_orbitals() const;

        /**
         * @brief Gets the number of electrons.
         * @return int Number of electrons.
         */
        int get_n_electrons() const;

private:
        //----------------------------------------------------------------------------
        //     PRIVATE MEMBERS
        //----------------------------------------------------------------------------

        std::string filename;                   ///< Path to the Hamiltonian file.
        int num_qubits = 0;                     ///< Number of qubits.
        int n_electrons = 0;                    ///< Number of electrons.
        std::vector<std::string> pauli_strings; ///< Stored Pauli strings.
        std::vector<qcomp> coefficients;        ///< Stored coefficients.
        PauliStrSum quest_hamiltonian;          ///< QuEST object.

        //----------------------------------------------------------------------------
        //     INTERNAL METHODS
        //----------------------------------------------------------------------------

        /**
         * @brief Loads and parses the Hamiltonian from the JSON file.
         */
        void load_hamiltonian();

        /**
         * @brief Parses a coefficient string into a complex number.
         * @param coeff_str String rep (e.g., "(1+0j)").
         * @return qcomp Parsed complex number.
         */
        qcomp parse_coefficient(const std::string &coeff_str);
};
